version: '3.9'
services:
  nest-api:
    build:
      context: .
      target: dev
      dockerfile: Dockerfile
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore: ['node_modules/', 'logs/']
        - action: rebuild
          path: package.json
    image: nowaylifer/home-library
    restart: always
    container_name: nest-api
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${PGPORT}/${POSTGRES_DB}?schema=public
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    container_name: db
    restart: always
    ports:
      - '${PGPORT}:${PGPORT}'
    env_file:
      - .env
    volumes:
      - pg-data:/var/lib/postgresql/data
      - pg-logs:/var/log/postgresql
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'pg_isready']
      start_interval: 2s
      start_period: 20s
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app-network:
    driver: bridge

volumes:
  pg-data:
  pg-logs:
